# Generated by Django 5.1.6 on 2025-02-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('fname', models.CharField(max_length=100)),
                ('mname', models.CharField(max_length=100)),
                ('dob', models.DateField(max_length=100)),
                ('bloodgrp', models.CharField(max_length=50)),
                ('specialisation', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField(max_length=50)),
                ('session', models.IntegerField(max_length=50)),
                ('rollno', models.IntegerField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
